repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
        - id: end-of-file-fixer
        - id: trailing-whitespace
        - id: check-added-large-files
        - id: check-merge-conflict
        - id: detect-private-key
        - id: requirements-txt-fixer
        - id: check-json
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.5
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v7.32.0  # Use the ref you want to point at
    hooks:
      - id: eslint
        files: \.[jt]sx?$  # This will run ESLint on .js, .ts, .jsx and .tsx files
        types: [file]
        additional_dependencies:
        -   eslint@8.57.0
        -   typescript-eslint@7.11.0
        -   eslint-config-next@14.2.1
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2  # Use the latest version available
    hooks:
      - id: mypy
        args: ["--strict", --ignore-missing-imports]  # Use strict mode to enforce type checking
        additional_dependencies:
          - "pydantic>=1.10.4"
          - "fastapi>=0.68.0"
