[project]
name = "ferntree"
version = "0.1.0"
authors = [
    { name = "felixtgd", email = "felix.tangerding@pm.me" }
]
requires-python = ">=3.12"
dependencies = [
    "aiohttp==3.14.3",
    "datetime==5.5.0",
    "fastapi>=0.141.1",
    "numpy>=2.5.3",
    "pandas>=3.0.5",
    "pre-commit==3.7.0",
    "psycopg-pool==3.3.1",
    "psycopg[binary]==3.3.5",
    "pydantic>=2.13.5",
    "pytest==8.4.2",
    "pytest-asyncio==1.2.0",
    "python-dotenv==1.2.2",
    "uvicorn==0.29.0",
]

[tool.uv]
package = false

[tool.ruff]
# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
    "mlflow_export_import"
]

# Assume Python 3.12.
target-version = "py312"

[tool.ruff.lint]
# Enable pycodestyle (`E`) and Pyflakes (`F`) codes by default.
select = ["E", "F", "D", "I"]

# Ignoring D416 and D406 since we haven't settled on a docstring convention yet.
ignore = ["F821", "F405", "F403", "D100", "D104", "D203", "D205", "D213", "D401", "D406", "D416", "D407"]

# Allow autofix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"
