import os

from dotenv import load_dotenv

from pymongo import MongoClient
from pymongo.server_api import ServerApi
import certifi

# Use certifi to get the path of the CA file
ca = certifi.where()

# Load config from .env file:
scipt_dir = os.path.dirname(os.path.abspath(__file__))
env_path = os.path.join(
    scipt_dir, "../../../../.env"
)  # TODO: Improve this! Path not cool
load_dotenv(env_path)
MONGODB_URI = os.environ["MONGODB_URI"]
MONGODB_DATABASE = os.environ["MONGODB_DATABASE"]


class pyMongoClient:
    def __init__(self):
        self.client = MongoClient(MONGODB_URI, server_api=ServerApi("1"), tlsCAFile=ca)
        self.db = self.client[MONGODB_DATABASE]

    def insert_one(self, collection: str, document: dict):
        # Insert a document into the collection
        collection = self.db[collection]
        result = collection.insert_one(document)

        # Return the _id of the inserted document which was generated by MongoDB
        return str(result.inserted_id)

    def find_one(self, collection: str, query: dict):
        # Find a document in the collection
        collection = self.db[collection]
        result = collection.find_one(query)

        return result

    async def close(self):
        self.client.close()
